### ISSUE TITLE
能添加一个结果排序的功能吗

### ISSUE THREAD

**Issue by Sizisa** [Greenplumwine/utools-MavenSearch#1]
可以让搜索结果按照 使用数量 排序吗？比如搜索lombok，第一个不是要用的，甚至第一页都没有

**Comment by Greenplumwine** [comment]
> 可以让搜索结果按照使用数量排序吗？或者搜索lombok，第一个不是要用的，甚至第一页都没有

尽可能满足吧，毕竟使用的是阿里的仓库，在阿里仓库里面没有这些，我会在找一些其他maven仓库的api，将阿里进行替换，如果你有比较好的仓库地址，不要带验证token、cookie等，可以发给我，我会进行解析

**Comment by Greenplumwine** [comment]
> 可以让搜索结果按照使用数量排序吗？或者搜索lombok，第一个不是要用的，甚至第一页都没有

尽可能满足吧，毕竟使用的是阿里的仓库，在阿里仓库里面没有这些，我会在找一些其他maven仓库的api，将阿里进行替换，如果你有比较好的仓库地址，不要带验证token， cookie等，可以发给我，我会进行解析

**Comment by Sizisa** [comment]
谢谢回复，暂时没有好的仓库，帮不上什么忙了

**Comment by Greenplumwine** [comment]
> 谢谢回复，暂时没有好的仓库，帮不上什么忙了

没关系，我会站在找找，距离下次更新的时间比较长，非常抱歉给你带来不好的体验

**Comment by Sizisa** [comment]
还是谢谢你，这已经方便了很多了

**Comment by Greenplumwine** [comment]
兄弟，项目开始审核了，这次我还了sonatype的仓库，应该是自带排序的，我自己看json的时候发现比较常用的都在前面，utools上的正在审核，审核后可以再次尝试，如果有什么问题，你可以在给我反馈
